// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhLJgjRbwyvZyIhnsfuJ8IThTOPWVjJco',
    appId: '1:304040222407:web:4633e43d7a9bc48f62e8e2',
    messagingSenderId: '304040222407',
    projectId: 'roadrunner-2230f',
    authDomain: 'roadrunner-2230f.firebaseapp.com',
    storageBucket: 'roadrunner-2230f.firebasestorage.app',
    measurementId: 'G-KQTQKS5R29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj_27qEAafMqEFmNQLUg7prT_uDerPa24',
    appId: '1:304040222407:android:10639b7293c62d9662e8e2',
    messagingSenderId: '304040222407',
    projectId: 'roadrunner-2230f',
    storageBucket: 'roadrunner-2230f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6N1Cf-GlrB08Aa6ZyGQRnoJWCjGSCz8',
    appId: '1:304040222407:ios:d1b86bdb8aef348762e8e2',
    messagingSenderId: '304040222407',
    projectId: 'roadrunner-2230f',
    storageBucket: 'roadrunner-2230f.firebasestorage.app',
    iosClientId: '304040222407-mnddmri1fk6ii3eeukl26rml7mumovur.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadRunnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa6N1Cf-GlrB08Aa6ZyGQRnoJWCjGSCz8',
    appId: '1:304040222407:ios:d1b86bdb8aef348762e8e2',
    messagingSenderId: '304040222407',
    projectId: 'roadrunner-2230f',
    storageBucket: 'roadrunner-2230f.firebasestorage.app',
    iosClientId: '304040222407-mnddmri1fk6ii3eeukl26rml7mumovur.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadRunnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhLJgjRbwyvZyIhnsfuJ8IThTOPWVjJco',
    appId: '1:304040222407:web:1f1a278052878a5562e8e2',
    messagingSenderId: '304040222407',
    projectId: 'roadrunner-2230f',
    authDomain: 'roadrunner-2230f.firebaseapp.com',
    storageBucket: 'roadrunner-2230f.firebasestorage.app',
    measurementId: 'G-0QSZ1WCL1X',
  );
}
